version: "3.10"
services:
  worker:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - FORCE_SUB=${FORCE_SUB}
      - ADMIN=${ADMIN}
      - DB_URL=${DB_URL}
      - DB_NAME=${DB_NAME}
